// ssn/frontend-react16/src/components/layout.jsx
import React from "react";
import { connect } from "react-redux";
import AppBar from '@material-ui/core/AppBar'
import Toolbar from '@material-ui/core/Toolbar';
import Typography from '@material-ui/core/Typography';
import { LOGGED_USER } from "../globals";

class Layout extends React.Component {

    render() {
        return (
            <React.Fragment>
                <AppBar position="fixed">
                    <Toolbar>
                        <Typography variant="h5" style={{ flex:1 }}>
                            Simple Social Network
                        </Typography>
                        <Typography variant="subtitle1">
                            { LOGGED_USER }
                        </Typography>
                    </Toolbar>
                </AppBar>
            </React.Fragment>
        );
    }
}

function mapStateToProps(state) {
    return {
        loggedUser: state.loggedUser,
        currentUser: state.currentUser,
        title: state.title,
		friends: state.friends
    };
}

let mapDispatchToProps = {};

export default connect(mapStateToProps,mapDispatchToProps)(Layout);

// ssn/frontend-angular8/src/components/layout/layout.component.ts
import { Component } from "@angular/core";
import { LOGGED_USER } from "../../globals";

@Component({
	selector: 'layout',
	templateUrl: './layout.component.html'
})
export class LayoutComponent {
	
	loggedUser:string = LOGGED_USER;
	
}

<mat-toolbar color="primary" style="position:fixed;top:0;z-index:1000" [class.mat-elevation-z8]="true">
    <h1 class="md-display-3" style="flex:1">Simple Social Network</h1>
    <span class="md-body-2">{{ loggedUser }}</span>
</mat-toolbar>
