// ssn/frontend-angular8/src/components/comment-list/comment-list.component.ts
import { Component, Input } from "@angular/core";
import { Comment } from "../../data-types";
import { message } from "../../messages";

@Component({
	selector: "comment-list",
	templateUrl: "./comment-list.component.html",
	styles: []
})
export class CommentListComponent {
	@Input() comments: Comment[];
	@Input() save: Function;

	placeholderMessage: string = message("writeNewComment");
	commentMessage: string = message("comment");
}

	<div *ngFor="let comment of comments">
		<comment [comment]="comment"></comment>
	</div>
	<div>
		<post-editor [saveContent]="save" [placeholder]="placeholderMessage" [title]="commentMessage"></post-editor>
	</div>

// ssn/frontend-react16/src/components/comment-list.jsx
import React from "react";
import Grid from "@material-ui/core/Grid";
import Comment from "./comment.jsx";
import PostEditor from "./post-editor.jsx";
import grey from '@material-ui/core/colors/grey';
import { message } from "../messages";

class CommentList extends React.Component {
	render() {
		return (
			<Grid container spacing="2" style={{ backgroundColor: grey[200] }}>
				{this.props.comments.map(comment => 
					<Grid item xs="12">
						<Comment comment={comment} />
					</Grid>
				)}
				<Grid item xs="12">
					<PostEditor title={message("comment")}
										save={this.props.save}
										placeholder={message("writeNewComment")}
									/>
				</Grid>
			</Grid>
		);
	}
}

export default CommentList;
