// ssn/frontend-angular8/src/components/comment/comment.component.ts
import { Component, Input, OnInit } from "@angular/core";
import { Comment } from "../../data-types";
import { formatTimestamp } from "../../utils/data-formatter";

@Component({
	selector: "comment",
	templateUrl: "./comment.component.html",
	styles: []
})
export class CommentComponent implements OnInit {
	@Input() comment: Comment;

	timestamp:string;

	ngOnInit() {
		this.timestamp = formatTimestamp(this.comment.timestamp);
	}

}

<div style="margin-bottom:20px">
	<div class="mat-body-2" style="font-style:italic;white-space:pre-wrap">
		{{ comment.user }}, {{ timestamp }}
	</div>
	<div class="mat-body-2" style="font-weight:bold;white-space:pre-wrap">
		{{ comment.content }}
	</div>
</div>

// ssn/frontend-react16/src/components/comment.jsx
import React from "react";
import Box from "@material-ui/core/Box";
import Typography from "@material-ui/core/Typography";
import { formatTimestamp } from "../utils/data-formatter";

class Comment extends React.Component {
	render() {
		return (
			<Typography variant="body2">
				<Box style={{ fontStyle: "italic", marginLeft:10 }}>
					{this.props.comment.user}, {formatTimestamp(this.props.comment.timestamp)}
				</Box>
				<Box style={{ fontWeight:"bold", marginLeft:10, whiteSpace: "pre-wrap" }}>
					{this.props.comment.content}
				</Box>
			</Typography>
		);
	}
}

export default Comment;
