// ssn/frontend-angular8/src/components/friends/friends.component.ts
import { Component, Input, OnInit } from "@angular/core";
import { Router } from "@angular/router";
import { UsersService } from "../../services/users.service";
import { PostsService } from "../../services/posts.service";
import { message } from "../../messages";

@Component({
	selector: "friends",
	templateUrl: "./friends.component.html",
	styles: []
})
export class FriendsComponent implements OnInit {
	@Input() friends: string[];

	friendsMessage: string = message("friends");

	constructor(private router: Router, private usersService:UsersService, private postService:PostsService) {}

	ngOnInit() {
		this.usersService.getFriends().subscribe(friends => this.friends = friends);
	}

	loadPosts = (friend:string) => {
		this.usersService.setCurrentUser(friend);
		this.postService.getPosts(friend);
		this.router.navigateByUrl("/dashboard");
	}
}

<mat-card class="background-blue-800">
	<mat-card-header style="color:white">
		{{friendsMessage}}
	</mat-card-header>
	<mat-divider></mat-divider>
	<mat-card-content>
		<mat-nav-list>
			<mat-list-item *ngFor="let friend of friends">
				<a matLine (click)="loadPosts(friend)" style="color:yellow">
					<p class="friends-list-user">{{ friend }}</p>
				</a>
			</mat-list-item>
		</mat-nav-list>
	</mat-card-content>
</mat-card>

// ssn/frontend-react16/src/components/friends.jsx
import React from "react";
import { connect } from "react-redux";
import Card from "@material-ui/core/Card";
import CardHeader from '@material-ui/core/CardHeader';
import List from "@material-ui/core/List";
import Divider from "@material-ui/core/Divider";
import ListItem from "@material-ui/core/ListItem";
import { getPosts, setCurrentUser } from "../redux/actions";
import { Redirect } from "react-router-dom";
import { ListItemText, CardContent } from "@material-ui/core";
import blue from '@material-ui/core/colors/blue'
import { message } from "../messages";

class Friends extends React.Component {
	constructor(props) {
		super(props);
		this.state = {
			redirect: false
		};
	}

	loadPosts = friend => {
		this.props.setCurrentUser(friend);
		this.props.getPosts(friend);
		this.setState({ redirect: true });
	}

	render() {
		if (this.state.redirect) {
			this.setState({ redirect: false });
			return <Redirect to={"/dashboard" } />;
		}
		
		let friendsListElement;
		if (this.props.friends) {
			friendsListElement = this.props.friends.map(friend => (
				<ListItem
					key={friend}
					button
					onClick={() => this.loadPosts(friend)}
				>
					<ListItemText primary={friend} />
				</ListItem>
			));
		}

		return (
			<Card style={{ backgroundColor: blue[800] }}>
				<CardHeader title={message("friends")} style={{ color: "white"}} />
				<Divider/>
				<CardContent style={{ color: "yellow" }}>
					<List component="nav">
						{friendsListElement}
					</List>
				</CardContent>
			</Card>
		);
	}
}

function mapStateToProps(state) {
	return {
		friends: state.friends
	};
}

let mapDispatchToProps = { getPosts, setCurrentUser };

export default connect(mapStateToProps,mapDispatchToProps)(Friends);
